drop table [s_credit_limit]
drop table [t_credit_limit]

drop table [s_ar_open_items]
drop table [t_ar_open_items]


CREATE TABLE [dbo].[t_ar_open_items](
	[AR_OpenItem_ID] [varchar](60) NULL,
	[Interface_ID] [varchar](18) NULL,
	[Company_Code] [varchar](18) NULL,
	[Customer] [varchar](20) NULL,
	[Special_GL_IND] [varchar](14) NULL,
	[Clearing_Date] [varchar](12) NULL,
	[Clearing_Doc] [varchar](30) NULL,
	[Assignment] [varchar](30) NULL,
	[Fiscal_Year1] [varchar](14) NULL,
	[Doc_No] [varchar](12) NULL,
	[Line_Item1] [varchar](12) NULL,
	[Posting_Date] [varchar](12) NULL,
	[Doc_Date1] [varchar](12) NULL,
	[Entry_Date] [varchar](12) NULL,
	[Currency] [varchar](18) NULL,
	[Local_Currency] [varchar](18) NULL,
	[Reference1] [varchar](30) NULL,
	[Doc_Type] [varchar](20) NULL,
	[Posting_Period] [varchar](20) NULL,
	[Posting_Key] [varchar](20) NULL,
	[Debit_Credit_Ind] [varchar](20) NULL,
	[Business_Area] [varchar](20) NULL,
	[Tax_Code2] [varchar](20) NULL,
	[Amount_In_LC] [numeric](16, 2) NULL,
	[Amount1] [numeric](16, 2) NULL,
	[LC_Tax_Amount] [numeric](16, 2) NULL,
	[Tax_Amount] [numeric](16, 2) NULL,
	[Text] [text] NULL,
	[Branch_Account] [varchar](16) NULL,
	[Baseline_Payment_Date] [varchar](12) NULL,
	[Payment_Terms] [varchar](12) NULL,
	[Days1] [int] NULL,
	[Days2] [int] NULL,
	[Days_Net] [int] NULL,
	[Discpercent1] [numeric](16, 2) NULL,
	[Discpercent2] [numeric](16, 2) NULL,
	[Disc_Base] [numeric](16, 2) NULL,
	[Cash_Disc_Amount] [numeric](16, 2) NULL,
	[Cash_Disc] [numeric](16, 2) NULL,
	[Payment_Method] [varchar](14) NULL,
	[Payment_Block] [varchar](14) NULL,
	[Fixed] [varchar](14) NULL,
	[Invoice_Ref] [varchar](14) NULL,
	[Fiscal_Year2] [varchar](14) NULL,
	[Line_Item2] [int] NULL,
	[Dunning_Block] [varchar](16) NULL,
	[Dunning_Key] [varchar](16) NULL,
	[Last_Dunned] [varchar](12) NULL,
	[Dunning_Level] [int] NULL,
	[Dunning_Area] [varchar](18) NULL,
	[Doc_Status] [varchar](14) NULL,
	[Follow_On_Doc_Type] [varchar](14) NULL,
	[VAT_Registration_No] [nvarchar](30) NULL,
	[Reason_Code] [varchar](16) NULL,
	[Pmt_Meth_Supplement] [varchar](16) NULL,
	[Ref_Key1] [varchar](16) NULL,
	[Ref_Key2] [varchar](16) NULL,
	[Gen_Ledger_Currency] [varchar](16) NULL,
	[Amount2] [numeric](16, 2) NULL,
	[Payment_Amount] [numeric](16, 2) NULL,
	[Name1] [nvarchar](60) NULL,
	[Name2] [nvarchar](60) NULL,
	[Name3] [nvarchar](60) NULL,
	[Name4] [nvarchar](60) NULL,
	[Postal_Code] [varchar](16) NULL,
	[City] [varchar](14) NULL,
	[Country] [varchar](14) NULL,
	[Street] [nvarchar](60) NULL,
	[PO_Box] [varchar](14) NULL,
	[PB_Postal_Code] [varchar](14) NULL,
	[Post_Bank_Acct_No] [varchar](20) NULL,
	[Bank_Account] [varchar](20) NULL,
	[Bank_Key] [varchar](20) NULL,
	[Bank_Country] [varchar](16) NULL,
	[Tax_No1] [varchar](12) NULL,
	[Tax_No2] [varchar](12) NULL,
	[Liable_For_VAT] [varchar](12) NULL,
	[Sales_Equalizatn_Tax] [varchar](12) NULL,
	[Region] [varchar](12) NULL,
	[Bank_Control_Key] [varchar](12) NULL,
	[Instruction_Key] [varchar](14) NULL,
	[Payment_Recipient] [nvarchar](60) NULL,
	[Language_Key] [varchar](18) NULL,
	[Bill_Of_Exch_Life] [numeric](16, 2) NULL,
	[BOE_Tax_Code] [varchar](14) NULL,
	[Bill_Exchange_Tax_LC] [numeric](16, 2) NULL,
	[Bill_Of_Exchange_Tax] [numeric](16, 2) NULL,
	[LC_Collection_Charge] [numeric](16, 2) NULL,
	[Collection_Charge] [numeric](16, 2) NULL,
	[Tax_Code1] [varchar](16) NULL,
	[Issue_Date] [varchar](12) NULL,
	[Used_On] [varchar](12) NULL,
	[Planned_Usage] [nvarchar](100) NULL,
	[Domicile] [varchar](14) NULL,
	[Drawer] [varchar](100) NULL,
	[Cenbank_Loc] [varchar](50) NULL,
	[City_Of_BOE_Drawer] [varchar](50) NULL,
	[Drawee] [varchar](100) NULL,
	[City_Of_Drawee] [varchar](50) NULL,
	[Disc_Days] [int] NULL,
	[Disc_Rate] [varchar](14) NULL,
	[Bill_Of_Exchange_Acpd] [varchar](14) NULL,
	[Bill_Ex_Status] [varchar](14) NULL,
	[Bill_Protest_ID] [varchar](18) NULL,
	[Bill_On_Demand] [varchar](18) NULL,
	[Ref_Procedure] [varchar](12) NULL,
	[Ref_Doc] [varchar](14) NULL,
	[Ref_Org_Unit] [varchar](16) NULL,
	[Reversed_With] [varchar](14) NULL,
	[Sp_GL_Transtype] [varchar](16) NULL,
	[Negative_Posting] [varchar](14) NULL,
	[Reference2] [varchar](16) NULL,
	[Billing_Doc] [varchar](16) NULL,
	[Reference3] [varchar](16) NULL,
	[Doc_Date2] [varchar](12) NULL,
	[Net_Due_Date] [varchar](20) NULL,
	[Buying_Group] [varchar](20) NULL,
	[Name6] [nvarchar](60) NULL,
	[Over_Due_Days] [varchar](16) NULL,
	[CreatedDate] [varchar](12) NULL,
	[CreatedBy] [varchar](20) NULL,
	[LastModifiedDate] [varchar](20) NULL,
	[LastModifiedBy] [varchar](20) NULL,
	[Is_Active] [int] NULL
)

CREATE TABLE [dbo].[s_ar_open_items](
	[AR_OpenItem_ID] [varchar](60) NULL,
	[Interface_ID] [varchar](18) NULL,
	[Company_Code] [varchar](18) NULL,
	[Customer] [varchar](20) NULL,
	[Special_GL_IND] [varchar](14) NULL,
	[Clearing_Date] [varchar](12) NULL,
	[Clearing_Doc] [varchar](30) NULL,
	[Assignment] [varchar](30) NULL,
	[Fiscal_Year1] [varchar](14) NULL,
	[Doc_No] [varchar](12) NULL,
	[Line_Item1] [varchar](12) NULL,
	[Posting_Date] [varchar](12) NULL,
	[Doc_Date1] [varchar](12) NULL,
	[Entry_Date] [varchar](12) NULL,
	[Currency] [varchar](18) NULL,
	[Local_Currency] [varchar](18) NULL,
	[Reference1] [varchar](30) NULL,
	[Doc_Type] [varchar](20) NULL,
	[Posting_Period] [varchar](20) NULL,
	[Posting_Key] [varchar](20) NULL,
	[Debit_Credit_Ind] [varchar](20) NULL,
	[Business_Area] [varchar](20) NULL,
	[Tax_Code2] [varchar](20) NULL,
	[Amount_In_LC] [numeric](16, 2) NULL,
	[Amount1] [numeric](16, 2) NULL,
	[LC_Tax_Amount] [numeric](16, 2) NULL,
	[Tax_Amount] [numeric](16, 2) NULL,
	[Text] [text] NULL,
	[Branch_Account] [varchar](16) NULL,
	[Baseline_Payment_Date] [varchar](12) NULL,
	[Payment_Terms] [varchar](12) NULL,
	[Days1] [int] NULL,
	[Days2] [int] NULL,
	[Days_Net] [int] NULL,
	[Discpercent1] [numeric](16, 2) NULL,
	[Discpercent2] [numeric](16, 2) NULL,
	[Disc_Base] [numeric](16, 2) NULL,
	[Cash_Disc_Amount] [numeric](16, 2) NULL,
	[Cash_Disc] [numeric](16, 2) NULL,
	[Payment_Method] [varchar](14) NULL,
	[Payment_Block] [varchar](14) NULL,
	[Fixed] [varchar](14) NULL,
	[Invoice_Ref] [varchar](14) NULL,
	[Fiscal_Year2] [varchar](14) NULL,
	[Line_Item2] [int] NULL,
	[Dunning_Block] [varchar](16) NULL,
	[Dunning_Key] [varchar](16) NULL,
	[Last_Dunned] [varchar](12) NULL,
	[Dunning_Level] [int] NULL,
	[Dunning_Area] [varchar](18) NULL,
	[Doc_Status] [varchar](14) NULL,
	[Follow_On_Doc_Type] [varchar](14) NULL,
	[VAT_Registration_No] [nvarchar](30) NULL,
	[Reason_Code] [varchar](16) NULL,
	[Pmt_Meth_Supplement] [varchar](16) NULL,
	[Ref_Key1] [varchar](16) NULL,
	[Ref_Key2] [varchar](16) NULL,
	[Gen_Ledger_Currency] [varchar](16) NULL,
	[Amount2] [numeric](16, 2) NULL,
	[Payment_Amount] [numeric](16, 2) NULL,
	[Name1] [nvarchar](60) NULL,
	[Name2] [nvarchar](60) NULL,
	[Name3] [nvarchar](60) NULL,
	[Name4] [nvarchar](60) NULL,
	[Postal_Code] [varchar](16) NULL,
	[City] [varchar](14) NULL,
	[Country] [varchar](14) NULL,
	[Street] [nvarchar](60) NULL,
	[PO_Box] [varchar](14) NULL,
	[PB_Postal_Code] [varchar](14) NULL,
	[Post_Bank_Acct_No] [varchar](20) NULL,
	[Bank_Account] [varchar](20) NULL,
	[Bank_Key] [varchar](20) NULL,
	[Bank_Country] [varchar](16) NULL,
	[Tax_No1] [varchar](12) NULL,
	[Tax_No2] [varchar](12) NULL,
	[Liable_For_VAT] [varchar](12) NULL,
	[Sales_Equalizatn_Tax] [varchar](12) NULL,
	[Region] [varchar](12) NULL,
	[Bank_Control_Key] [varchar](12) NULL,
	[Instruction_Key] [varchar](14) NULL,
	[Payment_Recipient] [nvarchar](60) NULL,
	[Language_Key] [varchar](18) NULL,
	[Bill_Of_Exch_Life] [numeric](16, 2) NULL,
	[BOE_Tax_Code] [varchar](14) NULL,
	[Bill_Exchange_Tax_LC] [numeric](16, 2) NULL,
	[Bill_Of_Exchange_Tax] [numeric](16, 2) NULL,
	[LC_Collection_Charge] [numeric](16, 2) NULL,
	[Collection_Charge] [numeric](16, 2) NULL,
	[Tax_Code1] [varchar](16) NULL,
	[Issue_Date] [varchar](12) NULL,
	[Used_On] [varchar](12) NULL,
	[Planned_Usage] [nvarchar](100) NULL,
	[Domicile] [varchar](14) NULL,
	[Drawer] [varchar](100) NULL,
	[Cenbank_Loc] [varchar](50) NULL,
	[City_Of_BOE_Drawer] [varchar](50) NULL,
	[Drawee] [varchar](100) NULL,
	[City_Of_Drawee] [varchar](50) NULL,
	[Disc_Days] [int] NULL,
	[Disc_Rate] [varchar](14) NULL,
	[Bill_Of_Exchange_Acpd] [varchar](14) NULL,
	[Bill_Ex_Status] [varchar](14) NULL,
	[Bill_Protest_ID] [varchar](18) NULL,
	[Bill_On_Demand] [varchar](18) NULL,
	[Ref_Procedure] [varchar](12) NULL,
	[Ref_Doc] [varchar](14) NULL,
	[Ref_Org_Unit] [varchar](16) NULL,
	[Reversed_With] [varchar](14) NULL,
	[Sp_GL_Transtype] [varchar](16) NULL,
	[Negative_Posting] [varchar](14) NULL,
	[Reference2] [varchar](16) NULL,
	[Billing_Doc] [varchar](16) NULL,
	[Reference3] [varchar](16) NULL,
	[Doc_Date2] [varchar](12) NULL,
	[Net_Due_Date] [varchar](20) NULL,
	[Buying_Group] [varchar](20) NULL,
	[Name6] [nvarchar](60) NULL,
	[Over_Due_Days] [varchar](16) NULL,
	[CreatedDate] [varchar](12) NULL,
	[CreatedBy] [varchar](20) NULL,
	[LastModifiedDate] [varchar](20) NULL,
	[LastModifiedBy] [varchar](20) NULL,
	[Is_Active] [int] NULL
)

CREATE TABLE [dbo].[t_credit_limit](
	[Credit_Limit_ID] [varchar](60) NULL,
	[Company_Code] [varchar](6) NULL,
	[Business_Partner_ID] [varchar](12) NULL,
	[Name] [ntext] NULL,
	[Customer] [varchar](60) NULL,
	[Credit_Segment] [varchar](60) NULL,
	[Securitization_Amt] [numeric](18, 2) NULL,
	[Currency] [varchar](12) NULL,
	[No_Secured_Credit_Limit] [numeric](18, 2) NULL,
	[Group_Key] [varchar](60) NULL,
	[Description] [ntext] NULL,
	[Credit_Check_Rule] [varchar](40) NULL,
	[Risk_Class] [varchar](8) NULL,
	[Buying_Group] [varchar](60) NULL,
	[Buying_Group_Name] [ntext] NULL,
	[Open_Order] [numeric](18, 2) NULL,
	[Open_Invoice] [numeric](18, 2) NULL,
	[Delivery] [numeric](18, 2) NULL,
	[Billing] [numeric](18, 2) NULL,
	[Insurance] [numeric](18, 2) NULL,
	[Qualified] [numeric](18, 2) NULL,
	[Unqualified] [numeric](18, 2) NULL,
	[Credit_Mgmt_Blocked] [varchar](8) NULL,
	[Company_Code_Blocked] [varchar](8) NULL,
	[CreatedDate] [varchar](12) NULL,
	[CreatedBy] [varchar](20) NULL,
	[LastModifiedDate] [varchar](12) NULL,
	[LastModifiedBy] [varchar](20) NULL,
	[Is_Active] [int] NULL
)

CREATE TABLE [dbo].[s_credit_limit](
	[Credit_Limit_ID] [varchar](60) NULL,
	[Company_Code] [varchar](6) NULL,
	[Business_Partner_ID] [varchar](12) NULL,
	[Name] [ntext] NULL,
	[Customer] [varchar](60) NULL,
	[Credit_Segment] [varchar](60) NULL,
	[Securitization_Amt] [numeric](18, 2) NULL,
	[Currency] [varchar](12) NULL,
	[No_Secured_Credit_Limit] [numeric](18, 2) NULL,
	[Group_Key] [varchar](60) NULL,
	[Description] [ntext] NULL,
	[Credit_Check_Rule] [varchar](40) NULL,
	[Risk_Class] [varchar](8) NULL,
	[Buying_Group] [varchar](60) NULL,
	[Buying_Group_Name] [ntext] NULL,
	[Open_Order] [numeric](18, 2) NULL,
	[Open_Invoice] [numeric](18, 2) NULL,
	[Delivery] [numeric](18, 2) NULL,
	[Billing] [numeric](18, 2) NULL,
	[Insurance] [numeric](18, 2) NULL,
	[Qualified] [numeric](18, 2) NULL,
	[Unqualified] [numeric](18, 2) NULL,
	[Credit_Mgmt_Blocked] [varchar](8) NULL,
	[Company_Code_Blocked] [varchar](8) NULL,
	[CreatedDate] [varchar](12) NULL,
	[CreatedBy] [varchar](20) NULL,
	[LastModifiedDate] [varchar](12) NULL,
	[LastModifiedBy] [varchar](20) NULL,
	[Is_Active] [int] NULL
)